#!/usr/bin/tcsh -f
git add ./plots
git add ./plots/delta_beta_pip_c.eps
git add ./plots/pi_plus_sec3_p_vs_theta_c.pdf
git add ./plots/fill_empty260181.eps
git add ./plots/ECfid.eps
git add ./plots/elas_ratio_c.pdf
git add ./plots/5integ_cs_c.eps
git add ./plots/miss_comp.pdf
git add ./plots/fit_axi_w_460_186.pdf
git add ./plots/pi_plus_sec3_p_vs_theta.pdf
git add ./plots/angle_var22_1.eps
git add ./plots/pi_plus_sec3_p_vs_theta.eps
git add ./plots/delta_beta_pr_c.pdf
git add ./plots/miss_comp_c.eps
git add ./plots/zvert_2sector.eps
git add ./plots/datamc_199_4_2_5_0.eps
git add ./plots/elas_ratio_c1.pdf
git add ./plots/delta_beta_pip.pdf
git add ./plots/elas_ratio_c1.eps
git add ./plots/miss_comp_c.pdf
git add ./plots/zvert2sect_c.pdf
git add ./plots/datamc_199_4_2_5_0_c.pdf
git add ./plots/fit_axi_w_460_186.eps
git add ./plots/angle_var11_1.eps
git add ./plots/wq2.eps
git add ./plots/eineout.eps
git add ./plots/wq2.pdf
git add ./plots/delta_beta_pip.eps
git add ./plots/pi_plus_sec3_p_vs_theta_c.eps
git add ./plots/fill_empty260181.pdf
git add ./plots/eineout.pdf
git add ./plots/rad_corr_42_50_1_r.pdf
git add ./plots/1_r_42_50_c.eps
git add ./plots/ECfid.pdf
git add ./plots/rad_corr_42_50_1_r.eps
git add ./plots/angle_var22_1.pdf
git add ./plots/5integ_cs_c.pdf
git add ./plots/5integ_cs.pdf
git add ./plots/datamc_199_4_2_5_0_c.eps
git add ./plots/delta_beta_pr.pdf
git add ./plots/elas_ratio_c.eps
git add ./plots/zvert2sect_c.eps
git add ./plots/elastic_cross.pdf
git add ./plots/eps2pdf.sh
git add ./plots/zvert_2sector.pdf
git add ./plots/angle_var11_1.pdf
git add ./plots/delta_beta_pr.eps
git add ./plots/datamc_199_4_2_5_0.pdf
git add ./plots/ECfid.png
git add ./plots/elastic_cross.eps
git add ./plots/5integ_cs.eps
git add ./plots/miss_comp.eps
git add ./plots/delta_beta_pr_c.eps
git add ./plots/delta_beta_pip_c.pdf
git add ./plots/1_r_42_50_c.pdf
git add ./e1e_paper.tex
git add ./e1e_paper.bib
git add ./pictures
git add ./pictures/miss_en
git add ./pictures/miss_en/miss_en.C
git add ./pictures/miss_en/data_new_time_corr.root
git add ./pictures/miss_en/miss_en.pdf
git add ./pictures/rad_corr
git add ./pictures/rad_corr/no_rad.root
git add ./pictures/rad_corr/rad_corr_all_q2.pdf
git add ./pictures/rad_corr/avrg_radcor_new_eg.dat
git add ./pictures/rad_corr/no_rad_old.root
git add ./pictures/rad_corr/rad_old.root
git add ./pictures/rad_corr/radcor.pdf
git add ./pictures/rad_corr/radcorr.C
git add ./pictures/rad_corr/rad.root
git add ./pictures/rad_corr/conv_epstopdf.sh
git add ./pictures/rad_corr/rad_corr_avrg.pdf
git add ./pictures/fiducial_cuts
git add ./pictures/fiducial_cuts/test_proton_fiduch.root
git add ./pictures/fiducial_cuts/pim.pdf
git add ./pictures/fiducial_cuts/electrons.pdf
git add ./pictures/fiducial_cuts/th_vs_p_pip.pdf
git add ./pictures/fiducial_cuts/pip_fid_2dim.C
git add ./pictures/fiducial_cuts/p_fid_2dim.C
git add ./pictures/fiducial_cuts/protons.pdf
git add ./pictures/fiducial_cuts/th_vs_p_pip_1.C
git add ./pictures/fiducial_cuts/pim_fid_2dim.C
git add ./pictures/fiducial_cuts/pip.pdf
git add ./pictures/fiducial_cuts/fid_new2.C
git add ./pictures/mass_corr
git add ./pictures/mass_corr/out_cr_sec_eff.root
git add ./pictures/mass_corr/out_cr_sec_all_top.root
git add ./pictures/mass_corr/mass_corr.fig
git add ./pictures/mass_corr/mass_corr_factor.root
git add ./pictures/mass_corr/mass_corr_pspdftex.eps
git add ./pictures/mass_corr/mass_tex.pdf
git add ./pictures/mass_corr/out_cr_sec_phi.root
git add ./pictures/mass_corr/mass_tex.tex
git add ./pictures/mass_corr/mass_tex.log
git add ./pictures/mass_corr/mass_tex.aux
git add ./pictures/mass_corr/mass_tex.sh
git add ./pictures/mass_corr/mass_corr.C
git add ./pictures/mass_corr/out_cr_sec_all_top_mass_corr_eff.root
git add ./pictures/mass_corr/mass_corr.pspdftex
git add ./pictures/mass_corr/out_cr_sec_all_top_mass_corr_phi.root
git add ./pictures/mass_corr/mass_corr_pspdftex.pdf
git add ./pictures/mass_corr/out_cr_sec_all_top_mass_corr.root
git add ./pictures/qcheck
git add ./pictures/qcheck/qcheck1d.C
git add ./pictures/qcheck/qcheck1d.pdf
git add ./pictures/efficiency
git add ./pictures/efficiency/eff_err.pdf
git add ./pictures/efficiency/eff_err.root
git add ./pictures/efficiency/out_eff.root
git add ./pictures/efficiency/abbhhm.h
git add ./pictures/efficiency/data_rec.C
git add ./pictures/efficiency/saphir.h
git add ./pictures/efficiency/eff_avrg.C
git add ./pictures/efficiency/eff_err.C
git add ./pictures/efficiency/2pi_3pi.pdf
git add ./pictures/efficiency/data_rec_plot.pdf
git add ./pictures/efficiency/data_rec_old.root
git add ./pictures/efficiency/data_rec.root
git add ./pictures/efficiency/eff_plot.pdf
git add ./pictures/efficiency/PlotXsec3pi.C
git add ./pictures/electron_id
git add ./pictures/electron_id/new_ratio.root
git add ./pictures/electron_id/earth.C
git add ./pictures/electron_id/ph_vs_ph_cc.pdf
git add ./pictures/electron_id/ec_data.root
git add ./pictures/electron_id/ec.C
git add ./pictures/electron_id/poissonf.C
git add ./pictures/electron_id/ph_el.pdf
git add ./pictures/electron_id/phel_integr_fract.txt
git add ./pictures/electron_id/ec_sim.C
git add ./pictures/electron_id/ratio_qqq.C
git add ./pictures/electron_id/data_no_nphe.root
git add ./pictures/electron_id/ec_cut.pdf
git add ./pictures/electron_id/ph_el.C
git add ./pictures/electron_id/ec_sim_new.root
git add ./pictures/angles
git add ./pictures/angles/alpha1.pdf
git add ./pictures/binning
git add ./pictures/binning/q2vsw.C
git add ./pictures/binning/q2vsw.root
git add ./pictures/binning/q2vsw.pdf
git add ./pictures/hadron_id
git add ./pictures/hadron_id/b_vs_p_negative_time_corr.pdf
git add ./pictures/hadron_id/b_vs_p_time_corr.C
git add ./pictures/hadron_id/data_new_time_corr.root
git add ./pictures/hadron_id/b_vs_p_positiv_time_corr.pdf
git add ./pictures/hadron_id/b_vs_p_pim_time_corr.C
git add ./pictures/excl_cut
git add ./pictures/excl_cut/out_ind4_miss_data.root
git add ./pictures/excl_cut/miss_pim.C
git add ./pictures/excl_cut/miss_mass.pdf
git add ./pictures/eps2pdf.sh
git add ./pictures/vertex
git add ./pictures/vertex/test_zel_new.root
git add ./pictures/vertex/test_zel_new1.root
git add ./pictures/vertex/test_zel_new_old.root
git add ./pictures/vertex/vertex.pdf
git add ./pictures/vertex/test_zel.root
git add ./pictures/vertex/e1e_target_new.pdf
git add ./pictures/vertex/vertex.C
git add ./pictures/vertex/vertex_sim.C
git add ./pictures/vertex/data_test.root
git add ./pictures/vertex/vertex_sim.pdf
git add ./pictures/vertex/vertex_new.pdf
git add ./pictures/vertex/e1e_target.pdf
git add ./pictures/vertex/vertex_empty.pdf
git add ./pictures/vertex/vertex_empty.C
git add ./pictures/sys_err
git add ./pictures/sys_err/elastic
git add ./pictures/sys_err/elastic/sect1.pdf
git add ./pictures/sys_err/elastic/sect6.pdf
git add ./pictures/sys_err/elastic/sect2_new.pdf
git add ./pictures/sys_err/elastic/sect5.pdf
git add ./pictures/sys_err/elastic/sect6_new.pdf
git add ./pictures/sys_err/elastic/sect5_new.pdf
git add ./pictures/sys_err/elastic/elastic_cross_sect
git add ./pictures/sys_err/elastic/elastic_cross_sect/MyMainFrame.cxx
git add ./pictures/sys_err/elastic/elastic_cross_sect/plot_ratio.C
git add ./pictures/sys_err/elastic/elastic_cross_sect/macroDict.cxx
git add ./pictures/sys_err/elastic/elastic_cross_sect/mom_corrDict.h
git add ./pictures/sys_err/elastic/elastic_cross_sect/MyMainFrameDict.h
git add ./pictures/sys_err/elastic/elastic_cross_sect/elast_ratio_6_sectors.pdf
git add ./pictures/sys_err/elastic/elastic_cross_sect/elaslib.f
git add ./pictures/sys_err/elastic/elastic_cross_sect/macroDict.h
git add ./pictures/sys_err/elastic/elastic_cross_sect/mom_corrDict.cxx
git add ./pictures/sys_err/elastic/elastic_cross_sect/out_new.root
git add ./pictures/sys_err/elastic/elastic_cross_sect/opa_new
git add ./pictures/sys_err/elastic/elastic_cross_sect/Makefile
git add ./pictures/sys_err/elastic/elastic_cross_sect/out_ltime.root
git add ./pictures/sys_err/elastic/elastic_cross_sect/mom_corr.h
git add ./pictures/sys_err/elastic/elastic_cross_sect/opa_new_tbt
git add ./pictures/sys_err/elastic/elastic_cross_sect/MyMainFrame.h
git add ./pictures/sys_err/elastic/elastic_cross_sect/mom_corr.cxx
git add ./pictures/sys_err/elastic/elastic_cross_sect/MyMainFrameDict.cxx
git add ./pictures/sys_err/elastic/elastic_cross_sect/opa
git add ./pictures/sys_err/elastic/elastic_cross_sect/macro.cxx
git add ./pictures/sys_err/elastic/elastic_cross_sect/h10tot21
git add ./pictures/sys_err/elastic/elastic_cross_sect/out_ltime_notbt.root
git add ./pictures/sys_err/elastic/elastic_cross_sect/h10tot21.cxx
git add ./pictures/sys_err/elastic/elastic_cross_sect/macro.h
git add ./pictures/sys_err/elastic/sect4.pdf
git add ./pictures/sys_err/elastic/sect2.pdf
git add ./pictures/sys_err/elastic/sect1_new.pdf
git add ./pictures/sys_err/elastic/sect4_new.pdf
git add ./pictures/sys_err/elastic/sect3.pdf
git add ./pictures/sys_err/elastic/sect3_new.pdf
git add ./pictures/sys_err/cr_sect_Q2_04_045_int_stat_err.dat
git add ./pictures/sys_err/cr_sect_Q2_05_055_int_stat_err.dat
git add ./pictures/sys_err/cr_sect_Q2_05_055_int_stat_plus_sys_err.dat
git add ./pictures/sys_err/cr_sect_Q2_075_08_int_stat_err.dat
git add ./pictures/sys_err/cr_sect_Q2_045_05_int_stat_plus_sys_err.dat
git add ./pictures/sys_err/cr_sect_Q2_09_095_int_stat_plus_sys_err.dat
git add ./pictures/sys_err/cr_sect_Q2_065_07_int_stat_err.dat
git add ./pictures/sys_err/cr_sect_Q2_06_065_int_stat_err.dat
git add ./pictures/sys_err/cr_sect_Q2_085_09_int_stat_err.dat
git add ./pictures/sys_err/cr_sect_Q2_09_095_int_stat_err.dat
git add ./pictures/sys_err/out_cr_sec_all_top_final_bin_corr_eff.root
git add ./pictures/sys_err/cr_sect_Q2_06_065_int_stat_plus_sys_err.dat
git add ./pictures/sys_err/cr_sect_Q2_07_075_int_stat_plus_sys_err.dat
git add ./pictures/sys_err/cr_sect_Q2_08_085_int_stat_err.dat
git add ./pictures/sys_err/sys_err_new.png
git add ./pictures/sys_err/cr_sect_Q2_075_08_int_stat_plus_sys_err.dat
git add ./pictures/sys_err/out_cr_sec_all_top_final_bin_corr.root
git add ./pictures/sys_err/cr_sect_Q2_08_085_int_stat_plus_sys_err.dat
git add ./pictures/sys_err/cr_sect_Q2_065_07_int_stat_plus_sys_err.dat
git add ./pictures/sys_err/cr_sect_Q2_095_010_int_stat_err.dat
git add ./pictures/sys_err/cr_sect_Q2_085_09_int_stat_plus_sys_err.dat
git add ./pictures/sys_err/cr_sect_Q2_04_045_int_stat_plus_sys_err.dat
git add ./pictures/sys_err/cr_sect_Q2_095_010_int_stat_plus_sys_err.dat
git add ./pictures/sys_err/cr_sect_Q2_045_05_int_stat_err.dat
git add ./pictures/sys_err/cr_sect_Q2_07_075_int_stat_err.dat
git add ./pictures/sys_err/sys_err.pdf
git add ./pictures/sys_err/sys_err.C
git add ./pictures/sys_err/sys_err_new.pdf
git add ./pictures/sys_err/syserror
git add ./pictures/sys_err/syserror/test4.pdf
git add ./pictures/sys_err/syserror/test2.pdf
git add ./pictures/sys_err/syserror/test8.pdf
git add ./pictures/sys_err/syserror/test.pdf
git add ./pictures/sys_err/syserror/test1.pdf
git add ./pictures/sys_err/syserror/test3.pdf
git add ./pictures/sys_err/syserror/test6.pdf
git add ./pictures/sys_err/syserror/test7.pdf
git add ./pictures/sys_err/syserror/conv_epstopdf.sh
git add ./pictures/sys_err/sys_err_new.C
git add ./pictures/sys_err/all_q2.pdf
git add ./pictures/sys_err/cr_sect_Q2_055_06_int_stat_err.dat
git add ./pictures/sys_err/cr_sect_Q2_055_06_int_stat_plus_sys_err.dat
git add ./pictures/sys_err/hadronfiduch_shift
git add ./pictures/sys_err/hadronfiduch_shift/protonfiduch_plot_var.pdf
git add ./pictures/sys_err/hadronfiduch_shift/pionfiduch_plot_var.pdf
git add ./pictures/sys_err/hadronfiduch_shift/conv_epstopdf.sh
git add ./pictures/mom_corr
git add ./pictures/mom_corr/test_mom_corr2.root
git add ./pictures/mom_corr/test_mom_no_corr3.root
git add ./pictures/mom_corr/momcorr.C
git add ./pictures/mom_corr/test_mom_corr.root
git add ./pictures/mom_corr/proton_eloss
git add ./pictures/mom_corr/proton_eloss/sim_proton_mom_corr.root
git add ./pictures/mom_corr/proton_eloss/qqq
git add ./pictures/mom_corr/proton_eloss/eloss2d.pdf
git add ./pictures/mom_corr/proton_eloss/sim_mom_corr2.C
git add ./pictures/mom_corr/test_mom_corr1.root
git add ./pictures/mom_corr/el_sim_momcorr
git add ./pictures/mom_corr/el_sim_momcorr/plots
git add ./pictures/mom_corr/el_sim_momcorr/plots/gpp194testnew31.root
git add ./pictures/mom_corr/el_sim_momcorr/plots/sim_mom_corr.C
git add ./pictures/mom_corr/el_sim_momcorr/plots/el_sim_mom_corr.pdf
git add ./pictures/mom_corr/el_sim_momcorr/sim_mom_corr.C
git add ./pictures/mom_corr/el_sim_momcorr/sim_mom_corr.root
git add ./pictures/mom_corr/el_sim_momcorr/sim_mom_corr2.C
git add ./pictures/mom_corr/elast_pic_position.pdf
git add ./pictures/mom_corr/test_mom_corr3.root
git add ./pictures/mom_corr/test_mom_corr_test.root
git add ./pictures/mom_corr/elast_after_corr.pdf
git add ./pictures/mom_corr/elast_before_corr.pdf
git add ./pictures/mom_corr/test_mom_corr_test1.root
git add ./pictures/mom_corr/test_no_mom_corr.root
git add ./pictures/topologies
git add ./pictures/topologies/out_cr_sec_eff.root
git add ./pictures/topologies/cr_sec_pim.pdf
git add ./pictures/topologies/all_top_C.d
git add ./pictures/topologies/out_cr_sec_all_top.root
git add ./pictures/topologies/cr_sec_all_top.png
git add ./pictures/topologies/all_top.C
git add ./pictures/topologies/data_rec.C
git add ./pictures/topologies/pim_miss.C
git add ./pictures/topologies/out_cr_sec_pim.root
git add ./pictures/topologies/out_cr_sec_phi.root
git add ./pictures/topologies/cr_sec_pim.png
git add ./pictures/topologies/phi_distr.C
git add ./pictures/topologies/cr_sec_max_eff.pdf
git add ./pictures/topologies/cr_sec_all_top.pdf
git add ./pictures/topologies/max_eff.C
git add ./pictures/conclusions
git add ./pictures/conclusions/PlotXsec.C
git add ./pictures/conclusions/e1c04505.dat
git add ./pictures/conclusions/out_cr_sec_all_top_final_bin_corr_eff.root
git add ./pictures/conclusions/e1c05506.dat
git add ./pictures/conclusions/out_cr_sec_all_top_final_bin_corr.root
git add ./pictures/conclusions/e1c05055.dat
git add ./pictures/conclusions/e1c.dat
git add ./pictures/conclusions/ripani.dat
git add ./pictures/conclusions/e1e_e1c.pdf
git add ./pictures/conclusions/e1e_e1c.C
git add ./pictures/conclusions/e1e_e1c.png
git add ./e1e_paper.pdf
git add ./e1e_paper.sh
git add ./bibl.tex
